# -*- coding: utf-8 -*-
"""NLP Project pt 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1roNyGPtxl94XdqWrWJUco0XyZaejukZX
"""

import numpy as np
import pandas as pd

data=pd.read_excel("/content/speeches.xlsx")
print(data.head())

data.columns

from transformers import T5Tokenizer, T5ForConditionalGeneration, pipeline
import torch
import pandas as pd


# Combine relevant fields for fine-tuning
data['context'] = data['title'] + " " + data['transcript']

# Initialize tokenizer and model
tokenizer = T5Tokenizer.from_pretrained('t5-small')
model = T5ForConditionalGeneration.from_pretrained('t5-small')

# Fine-tune the model
def prepare_training_data(data, tokenizer):
    inputs = []
    outputs = []
    for idx, row in data.iterrows():
        inputs.append(f"question: <your-question> context: {row['context']}")
        outputs.append("<your-answer>")

    tokenized_inputs = tokenizer(inputs, max_length=512, truncation=True, padding="max_length", return_tensors="pt")
    tokenized_outputs = tokenizer(outputs, max_length=128, truncation=True, padding="max_length", return_tensors="pt")

    return tokenized_inputs, tokenized_outputs

inputs, outputs = prepare_training_data(data, tokenizer)

# Create PyTorch dataset
class QADataset(torch.utils.data.Dataset):
    def __init__(self, inputs, outputs):
        self.inputs = inputs
        self.outputs = outputs

    def __len__(self):
        return len(self.inputs["input_ids"])

    def __getitem__(self, idx):
        return {
            "input_ids": self.inputs["input_ids"][idx],
            "attention_mask": self.inputs["attention_mask"][idx],
            "labels": self.outputs["input_ids"][idx]
        }

train_dataset = QADataset(inputs, outputs)

# Fine-tuning parameters
from torch.utils.data import DataLoader
from transformers import AdamW

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
optimizer = AdamW(model.parameters(), lr=5e-5)


# Training loop
model.train()
for epoch in range(3):
    for batch in train_loader:
        optimizer.zero_grad()
        outputs = model(input_ids=batch['input_ids'],
                        attention_mask=batch['attention_mask'],
                        labels=batch['labels'])
        loss = outputs.loss
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch + 1} complete. Loss: {loss.item()}")

# Save the fine-tuned model
model.save_pretrained("fine_tuned_t5")
tokenizer.save_pretrained("fine_tuned_t5")

# Load the fine-tuned model for Q&A
qa_pipeline = pipeline("text2text-generation", model="fine_tuned_t5", tokenizer="fine_tuned_t5")

# Framework for chatbot interaction
def ask_bot(question):
    input_text = f"question: {question} context: " + " ".join(data['context'])
    response = qa_pipeline(input_text, max_length=512, truncation=True)
    return response[0]['generated_text']

# Example interaction
question = "What did Thomas Jefferson say about Congress in 1807?"
response = ask_bot(question)
print("Bot's response:", response)

